### ISSUE TITLE
openZeroVideoDelay

### ISSUE THREAD

**Issue by sunnylovejordan** [jdpxiaoming/ijkrtspdemo#3]
这个函数在jni层并没有找到实现的地方？

**Comment by jdpxiaoming** [comment]
https://blog.lxfpoe.work/jekyll/update/2020/09/19/ijkplayer07.html

**Comment by jdpxiaoming** [comment]
> 这个函数在jni层并没有找到实现的地方？

**Comment by sunnylovejordan** [comment]
博客里面写的 在这个repo里面 代码没实现，vp_duration 这个函数
